### ISSUE TITLE
postcss-loader如果sourceMap:true的话，/*px*/、/*no*/注释无效

### ISSUE THREAD

**Issue by 66beta** [songsiqi/px2rem-postcss#12]
vue-cli bulid/utils.js
```js
  /* ... */
  var cssLoader = {
    loader: 'css-loader',
    options: {
      minimize: process.env.NODE_ENV === 'production',
      sourceMap: options.sourceMap
    }
  },
  postcssLoader = {
    loader: 'postcss-loader',
    options: {
      sourceMap: false /*设为false才有效*/
    }
  }

  // generate loader string to be used with extract text plugin
  function generateLoaders (loader, loaderOptions) {
    var loaders = [cssLoader, postcssLoader]
    if (loader) {
      loaders.push({
        loader: loader + '-loader',
        options: Object.assign({}, loaderOptions, {
          sourceMap: options.sourceMap
        })
      })
    }
/* ... */
```

.postcsssrcjs
```js
module.exports = {
  "plugins": {
    'postcss-px2rem': {remUnit: 75},
    'postcss-cssnext': {}
  }
}
```

插件是生效了的
```css
[data-dpr="2"] .header-title {
    font-size: 0.48rem;
}

border-bottom: 0.013333rem solid rgba(95, 96, 108, .2);
```
如果sourceMap改成false的话就正常了
```css
[data-dpr="2"] .header-title {
    font-size: 36px;
}

border-bottom: 1px solid rgba(95, 96, 108, .2);
```

不知道为什么，望解答
