### ISSUE TITLE
px is converted to em when using with postcss-next

### ISSUE THREAD

**Issue by vvenv** [songsiqi/px2rem-postcss#8]
following:

``` css
.c-checkbox {
  height: 48px; /*px*/
  &.checked {
    transform: translate3d(32px, 0, 0); /*px*/
  }
}
```

will be converted to:

``` css
.c-checkbox {
  height: 0.64rem ;
}

.c-checkbox.checked {
  -webkit-transform: translate3d(0.426667rem, 0, 0);
  transform: translate3d(0.426667rem, 0, 0) ;
}
```

and that is NOT expected
